
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: ["health","info","hystrix.stream"]


SEARCH: 
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule

feign:  hystrix:    enabled: true
      
version: v1

spring:  application:    name: CUSTOMER-${version}
   

