server:
  port: 8762

eureka:
  instance:
    hostname: eureka8762.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://root:root@eureka8761.com:8761/eureka/
      
spring:
  application:    name: 04-Eureka  security:    user:      name: root
      password: root